### PR TITLE
Fix for NPC face colors

### PR DESCRIPTION
**Pull request by Touchyfoil**
Remove self:SetColor(GAMEMODE.WalkerColors[math.random(1, #GAMEMODE.WalkerColors)]) in npc_walker.lua and it will fix the issue npc face color issue.

### CODE REVIEW

**Comment by jacobgc** [comment]
However removing this would remove the colour on the NPCs but players would still get random colours.

**Comment by Touchyfoil** [comment]
Actually I have been using it like this and that has not happened. 
Also I didn't mean to close it that was an accident.

**Comment by jacobgc** [comment]
cl_init.lua line 143-149
function GM:NetworkEntityCreated( ent )
    if ent:GetClass() == "npc_walker" then
        ent.WalkerColor = Vector(ent:GetColor().r / 255, ent:GetColor().g / 255, ent:GetColor().b / 255)
        function ent:GetPlayerColor() return self.WalkerColor end
        function ent:RenderOverride() self:SetColor(Color(255,255,255,255)) self:DrawModel() end
    end
end

It seems like the walker colouring was moved. But not removed from the npc_walker.lua file.

**Comment by lolleko** [comment]
Thank you but this got fixed with the last update :)

**Pull request closed without merging**
